### ISSUE TITLE
Define MDN color scheme

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#137]
In https://github.com/schalkneethling/mdn-minimalist/issues/44 we are going to merge all of the current color variations into a single `scss` file. Once this is merged and the new version of Minimalist is published I will

1. [x] Create a page for our color scheme
2. [x] Expose *all* of the colors we currently have defined
3. [ ] Ask @malqinneh to assist in defining our actual color scheme based on these and any new colors
4. [ ] Once finalized, we need to then go back and clean up the color scheme inside Minimalist.

@mindy FYI, this is the style guide portion of https://github.com/schalkneethling/mdn-minimalist/issues/44

**Comment by malqinneh** [comment]
@schalkneethling amazing, thank you!
