### ISSUE TITLE
Integrate Webpack for JS, SASS and PostCSS

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#14]
Initially this will mostly be focused on compiling and bundling SaSS and replacing some SaSS functionality with PostCSS. As our JS codebase moves to using modern vanilla JS, Webpack can take over from plain Babeljs, to add additional tooling.

The most clearly definable benefit of this is better tooling, that leads to enhanced developer productivity. This sets up a modern workflow that allows for easier adoption of new features of the platform.

[1] https://webpack.js.org/loaders/
[2] https://webpack.js.org/loaders/sass-loader/
[3] https://webpack.js.org/loaders/postcss-loader/

**Comment by jwhitlock** [comment]
Bedrock has decided against webpack - https://github.com/mozilla/bedrock/issues/5417#issuecomment-385410257

**Comment by schalkneethling** [comment]
@jwhitlock Webpack would not be at the top of the priority list once I start prioritising these issues. I would like to start of with building a toolchain using NPM scripts as a start.

Once our JavaScript have moved over to ES6 modules I do think Webpack can add benefit.

**Comment by schalkneethling** [comment]
Another tool that I have been experimenting with, and that works pretty darn amazingly well is Parceljs - https://parceljs.org/

**Comment by schalkneethling** [comment]
Using Webpack for new React based front-end
