### ISSUE TITLE
Use Babeljs

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#15]
As a precursor to using Webpack, or in tandem while the JS is being converted, we should start using Babeljs as part of our front end toolchain.

This will allow us to use modern JavaScript, take advantage of the new syntax, features, and improved performance. Because we do not have to support a wide array of old browser versions, we can use a preset-env and target a specific list of browser/version combinations[2].

This will ensure that our compiled JS is still small enough to get performance gains over and above those we will gain during parsing and execution.

[1] https://babeljs.io/
[2] https://babeljs.io/docs/plugins/preset-env/#export-with-various-targets

**Comment by chrisdavidmills** [comment]
As a little thought here, I'd love to use Babel to transpile between modern ES syntax, and old-school JS syntax. So we can write all code examples using modern ES, but people can then still access older syntax versions if they need them. But we don't need to maintain both.

Would your work here facilitate that use case too? ;-)

**Comment by schalkneethling** [comment]
@chrisdavidmills Are you referring to the interactive examples here? If that is the case, Mark suggested something along those lines a while back:
https://github.com/mdn/interactive-examples/issues/265

So it is on the roadmap to do at some point I reckon.

**Comment by chrisdavidmills** [comment]
I was kinda suggesting it for any block of code, but I'll take what I can get ;-)

cheers!

**Comment by schalkneethling** [comment]
@chrisdavidmills It's an interesting idea, we should definitely keep this in the back of our minds. Perhaps we can chat a little more about this at the all hands as well.

**Comment by chrisdavidmills** [comment]
Sure thing man, let's do that.
