### ISSUE TITLE
💭 MDN design system inspiration 

### ISSUE THREAD

**Issue by mindy** [mdn/mdn-fiori#158]
**A place to collect thoughts, notes, resources, and inspiration for MDN's design system.** 

Some examples to get us started:

### 🦖 Mozilla
https://protocol.mozilla.org/

### 🎨 Adobe
Docs: https://spectrum.adobe.com/
Live examples: https://opensource.adobe.com/spectrum-css

### 🔺 Vercel  
https://vercel.com/design/collapse
☝️ Dark and light mode toggle

### 🗂 Atlassian
https://www.atlassian.design/guidelines/product/overview

### ❇️ Project Clarity
https://clarity.design/documentation/alerts

### Blueprint [[GitHub](https://github.com/palantir/blueprint)]
https://blueprintjs.com/docs/#blueprint/reading-the-docs
☝️ They're doing something we'd like to do, which is write components using TS, but be able to consume them in environments that do not use TS, like Kuma, which uses Flow. 

### 📙 Storybook's Design System ([GitHub](https://github.com/storybookjs/design-system)):
https://storybook-design-system.netlify.app
☝️ Great use of the `storybook-docs` addon. 

### 🤖 IBM ([GitHub](https://github.com/carbon-design-system/carbon/tree/master/packages/react)):
https://react.carbondesignsystem.com/
☝️ Worth looking at their `.storybook` configuration in GH

**Comment by mindy** [comment]
This PR has helpful Storybook view info. Posting this here so we don't lose track of it:
https://github.com/storybookjs/storybook/pull/9095

**Comment by schalkneethling** [comment]
Some more StoryDocs specific links:

- https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a
- https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
- https://github.com/storybookjs/design-system
