### ISSUE TITLE
U - Create [header] components and styles for desktop and mobile

### ISSUE THREAD

**Issue by tobinmori** [mdn/mdn-fiori#210]
**Acceptance Criteria**
- [ ] Added header components for desktop/mobile to storybook

**Comment by malqinneh** [comment]
Added https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/234 and included action items from this ticket to it. This user story can be closed @schalkneethling, let me know what you think.

**Comment by malqinneh** [comment]
Duplicate
