### ISSUE TITLE
🎨 T - Language selector

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#221]
For language selection in the header area of documentation pages, we have a custom-styled dropdown. See below:

![Screenshot 2020-07-10 at 12 03 24](https://user-images.githubusercontent.com/10350960/87142833-677f2680-c2a5-11ea-8493-440a2868900e.png)

## Implementation decision and next steps
- Add standard dropdown for language select
- Add [Add translation] link next to language select dropdown (desktop only)
![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/c3f6ffc7-9da9-41a3-bdb6-78bfd924940b)
- Keep dropdown for language select on mobile
- Truncate dropdown below [table of contents]/[jump to section] component
- Dropdown spans full width on mobile
![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/8f2c43f6-38d3-48d7-a1f0-e8819bb36499)

## Existing problems

The first downside between the current implementation and simply using a standard browser select element is that

1. It uses additional CSS and JavaScript to mimic a select element's dropdown behavior
2. There is not functional parity between it and a standard select and so, we lose some accessibility benefit we get for free when using a standard platform element

There is also a known problem on pages where there is a lot of available languages. As can be seen below, the dropdown extends beyond the viewport and a user needs to scroll the document to see all languages:

![Screenshot 2020-07-10 at 12 02 58](https://user-images.githubusercontent.com/10350960/87143178-f55b1180-c2a5-11ea-9116-30dd9bd5dec8.png)

One of the possible reasons we decided to use a custom dropdown is to accommodate the "Add a translation" option.

![Screenshot 2020-07-10 at 12 03 19](https://user-images.githubusercontent.com/10350960/87143275-1d4a7500-c2a6-11ea-9fc9-5b930cb19a15.png)

## Proposal

Use a standard select element for the languages, and provide move "Add a translation" to a button(this might be a feature we will loose entirely once the move to Github is complete)

For example:

![Screenshot 2020-07-10 at 12 13 03](https://user-images.githubusercontent.com/10350960/87143675-c2fde400-c2a6-11ea-9eff-de1bbabace61.png)

#### Expanded

![Screenshot 2020-07-10 at 12 16 46](https://user-images.githubusercontent.com/10350960/87143956-44ee0d00-c2a7-11ea-81be-f88a9becc096.png)

### Benefits

1. Simple to implement
2. Easy to maintain
3. Less CSS
4. Smaller DOM
5. Less JavaScript
6. Greater accessibility

**Comment by Gregoor** [comment]
I'm all for it, one of my life missions is fighting for standard dropdowns in places where custom ones don't add value (and have not been given the time+care to reach parity, like you said).

We could also have "add language" as an option inside the select, maybe with a divider: https://jsfiddle.net/ahv8zL5k/1/
Or alternatively using [`<optgroup>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup).

**Comment by schalkneethling** [comment]
> We could also have "add language" as an option inside the select, maybe with a divider: https://jsfiddle.net/ahv8zL5k/1/
> Or alternatively using [`<optgroup>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup).

For shizzle! I was thinking if we want to "detach" that functionality from the drop down, the button is an option.

**Comment by tobinmori** [comment]
+1 to @Gregoor's suggestion. Keeping all the options in the dropdown looks cleaner to me.

**Comment by malqinneh** [comment]
@Gregoor @schalkneethling @tobinmori 

Agree with Gregor's suggestion here, it keeps the breadcrumb area lighter. Here's how it could look like on Desktop:

![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/241a12c4-015b-491a-8f6c-921bde2b2119)

**Comment by schalkneethling** [comment]
Thank you @malqinneh. Desktop looks good. I just need to double-check whether we are potentially causing any accessibility issues here. The more I think of it, the more I am second-guessing my own recommendation here 😄 

I just might have a different suggestion here all together. Will get back to you ASAP.

**Comment by schalkneethling** [comment]
Ok, I have done some additional thinking, research and chatted with Marco Zehe. My recommendation then stands as initially proposed:

1. Change the language selector to be a standard HTML select element
2. Add a simple link to the right-hand side of the select field that links to "Add a Translation"

Reasons for separating out "Add translation" from the select dropdown

1. The way screen reader users use a select drop is not conducive to discovery and as such, they are more likely than not to completely miss the "Add a translation" option
2. The way the select element will be described to screen readers is a means to select your preferred language. This again does not indicate that there is a separate option to potentially add a translation if your preference is not available.
3. Selecting an item will for all but one option reload the current page and change the locale to the chosen locale. "Add a translation" on the other hand redirects the users to a completely different page
4. As we move forward with the new infrastructure of MDN we might have a static list of available languages that are machine translated but, we will definitely not keep the functionality of adding a new translation. Having the UI, styling, and JS for these two "features" separate makes a simpler to remove one and keep the other.

I hope this all makes sense. If everyone agrees with this, I reckon we are ready to solidify the final design and then move onto the implementation phase. Thank you o/\o

**Comment by malqinneh** [comment]
Thanks so much @schalkneethling -- especially sold on no. 4 in your list of reasons for separating out [add translation] from the select dropdown. On that note; would it be OK if we don't support [add translation] on mobile?

**Comment by schalkneethling** [comment]
> would it be OK if we don't support [add translation] on mobile?

100% - Our current system for this is definitely not usable/not meant for use on mobile devices. It is definitely a task that is done on desktop computers.

**Comment by malqinneh** [comment]
Got it. @schalkneethling just to confirm;

- Add language selector (desktop)
- Add language selector (mobile) 
- Add [Add translation] link next to language selector dropdown (desktop only)

Assuming we want to allow users to use the language dropdown on mobile. Is this correct?

**Comment by schalkneethling** [comment]
> Is this correct?

Correct.

**Comment by schalkneethling** [comment]
@malqinneh Thoughts?

![lang-selector](https://user-images.githubusercontent.com/10350960/88810546-c73a6480-d1b5-11ea-8d71-91c38c755267.png)

**Comment by malqinneh** [comment]
Keeping the original functionality of table of contents intact -- how about one these?

![Rectangle.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/6eeab43f-d6a7-49ec-a736-dea070eae053)

**Comment by schalkneethling** [comment]
Thanks, @malqinneh

I am torn between 3 and 7 😄 Leaning towards 3.

**Comment by malqinneh** [comment]
When comparing the two; there are no advantages to 7 (they both take up the same space / push content down the same distance).

**Comment by malqinneh** [comment]
@schalkneethling added some info under implementation decisions and next steps section in the description. Happy to revise as needed, let me know.

**Comment by schalkneethling** [comment]
Note that in terms of implementation, we will currently only implement this change in Kuma as Yari does not currently support any l10n.
