### ISSUE TITLE
Redesign layout of MDN Web Docs header

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#25]
This involves a rethink of the entire header of MDN Web Docs including location and interaction model for breadcrumbs, search, toc, quick lang switcher, page editing tools

Concepts have been proposed here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1446291

**Comment by schalkneethling** [comment]
From the bug:

> Hey All,
> 
> I have done some thinking and played around with different layouts for the header and will here attach three options. The first of these is my favourite but, let's open this up for voting and comment.
> 
> I took the opportunity to also look at the overall alignment of items in the header in relation to other items in the header as well as the main content. Let me know your thoughts. Thanks

### Option 1

![new-header-001](https://user-images.githubusercontent.com/10350960/57026977-61220300-6c3b-11e9-9fd6-47ada2e35867.png)

### Option 2

![new-header-002](https://user-images.githubusercontent.com/10350960/57026989-6c752e80-6c3b-11e9-965a-7711b29d60b6.png)

### Option 3

![new-header-004](https://user-images.githubusercontent.com/10350960/57026995-739c3c80-6c3b-11e9-964b-62f8d7cd4d9d.png)

**Comment by schalkneethling** [comment]
I would change the colours a little though:

![new-header-005](https://user-images.githubusercontent.com/10350960/57029216-5c604d80-6c41-11e9-9e8a-e36d005f9263.png)

**Comment by jmswisher** [comment]
With the darker color for the breadcrumbs/search bar, I would prefer Option 2 or 3. That dark color would really separate the title from the article in Option 1. I like the compactness of Option 2, but it might run into trouble with longer titles (e.g., in non-English languages).

**Comment by schalkneethling** [comment]
> With the darker color for the breadcrumbs/search bar, I would prefer Option 2 or 3. That dark color would really separate the title from the article in Option 1. I like the compactness of Option 2, but it might run into trouble with longer titles (e.g., in non-English languages).

Thank you for the feedback @jmswisher! I agree, with the darker colored bar, option 2 is my preference as well. @nickbrand, not to derail you, but would love your thoughts here when you have some free cycles. Nothing urgent.

**Comment by NickBrand** [comment]
You had me at hello

**Comment by schalkneethling** [comment]
> You had me at hello
> […](#)
> Sent from my iPhone

Whoops, wrong @NickBrandt

**Comment by schalkneethling** [comment]
There is a new header design on the beta site. There are still some aspects of the proposal here that I believe we should consider.

Here is the new header:

<img width="1549" alt="Screenshot 2019-06-11 at 11 51 30" src="https://user-images.githubusercontent.com/10350960/59262315-45991780-8c3f-11e9-8aba-62c195b7dd6c.png">

**Comment by nickbrandt** [comment]
@schalkneethling for some reason I didn't get a notification regarding your mention above, just now seeing this thread.

What concerns do you have with the updated design for the header area? Looks like we had similar ideas in terms of exposing search as well as the look of that even.

Here are some of my thoughts:
- I think it makes more sense to have breadcrumbs under the title of a page vs. above it.
- It is important to have the breadcrumbs as links (other than the current page item), to aid in navigating back if the user desires
- Putting search in the same area as the breadcrumbs (as in option 2) can cause space issues for smaller screens, especially when a user is deep within a section or within areas with longer titles.

**current beta site**
- The search placeholder text needs updated to be a little darker, as it's currently hard to read
- Icon for history (next to "edit" link) is not displayed correctly, and needs fixed

Let me know your thoughts!
