### ISSUE TITLE
T - Add breadcrumbs to Storybook

### ISSUE THREAD

**Issue by malqinneh** [mdn/mdn-fiori#259]
## Description
No changes from current implementation - same functionality currently on production documented in Storybook.

## Acceptance criteria
- [ ] Add component/style to Storybook
- [ ] Implement component/style on production

**Comment by peterbe** [comment]
For the record, [here's an interesting opinion gathering](https://github.com/mdn/yari/issues/978) about what you should do with a breadcrumb component if there are 0 parent links.
