### ISSUE TITLE
Optimise images and use best format

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#28]
> This is an item identified by @tkadlec as part of the performance audit

The homepage currently loads two GIF background images that could be better optimized if they were served as PNG’s.

### Hero background

https://developer.mozilla.org/static/img/home-bg.ca67b4ee8675.gif

As a gif: 9.6kb
As an 8-color PNG: 2.2kb

### Hero dino

https://developer.mozilla.org/static/img/home-dino.4c4029f73eb9.gif

As a gif: 26.7kb 
As an 8-color PNG: 9.2kb

**Comment by schalkneethling** [comment]
I have looked at both of these.

For the hero main background I get a total kb size of ~4.5kb using SVG. If we can get hold of the original source files we might be able to get even better results. The other big win using SVG for the hero background is that we can inline it, saving us another HTTP request.

For the dino head, I am wondering if we want to use webp with a fallback to png using `srcset`. Thought @tkadlec

**Comment by schalkneethling** [comment]
Seems PNG is definitely the best format for the dino head. In this case webp actually generates a slightly larger(~1kb) file.

**Comment by tkadlec** [comment]
Awesome! Just out of curiosity....have you run the SVG through SVGO to see if you can shave a little bit more off?

**Comment by tkadlec** [comment]
👍 Figured it was, but thought I'd verify. :)

**Comment by schalkneethling** [comment]
Closing as dupe of https://github.com/mdn/sprints/issues/340
