### ISSUE TITLE
Inline dnt-helper

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#31]
The `dnt-helper` utility almost never changes and it currently blocks rendering because of the HTTP request. It is therefore best to uglify and inline directly in the head of the document.

**Comment by schalkneethling** [comment]
Pull request: https://github.com/mozilla/kuma/pull/4881

**Comment by jwhitlock** [comment]
Duplicate of https://github.com/mdn/sprints/issues/257
