### ISSUE TITLE
Remove preload hints for iframe assets

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#32]
Having analysed some data during the recent performance audit, we noticed that instead of improving performance, the `preload` hints are having a detrimental effect on performance.

It looks to be causing a double download, or at the very least another set of requests from within the `iframe`. Because the `iframe` is not on the same domain as MDN Web Docs, it might very well be that they are not using the same browser cache. This means the preload really has no benefit.

Also, having done a test using local overrides in Chrome dev tools, the page showed a load performance improvement of 250ms with those `preload` hints removed. It is therefore best to remove them.

**Comment by schalkneethling** [comment]
Pull request: https://github.com/mozilla/kuma/pull/4878

**Comment by jwhitlock** [comment]
Merged and deployed to production.
