### ISSUE TITLE
Printing could be better aka Create print style sheet

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#50]
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1542834

@peterbe I actually didn't dare to actually print it out on paper so I used the Print to PDF on my mac. Could be that it looks different when sent to the actual HP printer.

![https://bug1542834.bmoattachments.org/attachment.cgi?id=9056645]

**Comment by peterbe** [comment]
> Could be that it looks different when sent to the actual HP printer.

Sure. Perhaps due to media queries that relate to the width. But likely to be minor differences in comparison to the bigger "flaws".
