### ISSUE TITLE
Names in the list of contributors are no longer clickable

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#89]
At the bottom of wiki pages on MDN Web Docs is a list of contributors to the page. Each individual name links to the person's profile on MDN on the current live site, but no longer does on the beta site. This is a regression.

## Bugzilla

https://bugzilla.mozilla.org/show_bug.cgi?id=1563478

**Comment by schalkneethling** [comment]
@peterbe @escattone @callahad I noticed this comment in the source:

```
/*
 * TODO: once we implement profile pages on the beta site
 * these contributor names should turn into links
 * <a href={`/${locale}/profiles/${c}`} rel="nofollow">{c}</a>
 */
```

I am guessing that we then need to change this issue to not block react-beta or, point these to the wiki. for now. Thoughts? @atopal

**Comment by atopal** [comment]
Let's point to the wiki for now.
