### ISSUE TITLE
No way to add a new translation to an existing page

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#93]
From Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1562858

## What did you do?

1. Went to https://beta.developer.mozilla.org/fr/docs/MDN/Doc_Status/JavaScript as I do almost daily
2. Searched for a recent page which is not available in French
3. Found https://beta.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Locale/caseFirst
4. Went to https://beta.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Locale/caseFirst
5. Tried to find a way to create the French version of it

## What happened?

Could not find a way to use a feature like "Add a translation" which usually brings the "$locales" then "$translate" views.

## What should have happened?

There should be a way to create a localized version of an English page if such a version does not already exists.

## Is there anything else we should know?

Writing directly this URL https://beta.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Locale/caseFirst$translate?tolocale=fr only brings a 404

As far as I can tell, there is no way to create a new localized page using beta.developer.mozilla.org

**Comment by schalkneethling** [comment]
@peterbe @escattone

We have the following bug on file:
https://bugzilla.mozilla.org/show_bug.cgi?id=1562858

The tl;dr is that the "Add a translation" link at the bottom of the languages drop down is missing from the React pages.

Looking at `buttons.html` I see that the link is wrapped in a conditional.

```
{% if document.is_localizable %}
```

I am guessing it is not shown on the React side because we do not have a way to query that status from React? Am I correct? If so, would it be possible to add that ability? Thanks!

**Comment by escattone** [comment]
@schalkneethling Yes, you're correct. If we decide we want to move forward with this, I'd like to take a crack at it. We would have to add `is_localizable` to the JSON returned by the document API, and then update the client/server-side React code paths to use it.
