### ISSUE TITLE
MDN Beta does not visually distinguish between current and obsolete / archived content

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#95]
From Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1563210

![Screenshot from 2019-07-03 14-01-48](https://user-images.githubusercontent.com/10350960/60656456-bfdc4680-9e4f-11e9-9baf-e5c2721544f0.png)

On the current site, archived pages have special styling to help warn users of obsolete content. On the Beta site, archived pages are displayed identically to normal, up-to-date articles.

Example:

https://developer.mozilla.org/en-US/docs/Archive/IdentityManager/get
https://beta.developer.mozilla.org/en-US/docs/Archive/IdentityManager/get
Archived content is listed at https://developer.mozilla.org/en-US/docs/Archive

**Comment by schalkneethling** [comment]
Looked in the code and it seems that this feature depends on the following:

```
{% set is_archive = (document.slug == 'Archive') or document.slug.startswith('Archive/') %}
```

It then includes the relevant stylesheet based on the result of `is_archive`:

```
{% if is_archive %}
  {% stylesheet 'archive' %}
{% endif %}
```

@escattone @peterbe I assume this is something that will need to be added to the document API?

**Comment by escattone** [comment]
@schalkneethling I don't think we need to add anything to the document API. The slug of the document is already available via the document API (see https://github.com/mozilla/kuma/blob/bd7581053f3840f5fa22b28e6372c729b0c3468f/kuma/javascript/src/document.jsx#L18), so for client-side navigations as well as server-side renders we can derive `is_archive` from that slug.
